[package]
name = "cyclonedx-bom"
version = "0.1.0"
authors = [ "Steve Springett <steve.springett@owasp.org>" ]
license = "Apache-2.0"
edition = "2018"

description = "CycloneDX Software Bill of Materials (SBOM) for Rust Crates"
homepage = "https://cyclonedx.org/"
repository = "https://github.com/CycloneDX/cyclonedx-rust-cargo"
readme = "README.md"

categories = ["command-line-utilities", "development-tools", "development-tools::cargo-plugins"]
keywords = ["sbom", "bom", "bill-of-materials", "components", "dependencies"]

[profile.release]
lto = true

[dependencies]
anyhow = "1.0.37"
cargo = "0.53.0"
chrono = { version = "0.4.19", features = ["serde"] }
lazy_static = "1.4.0"
packageurl = "0.2.0"
regex = "1.3.6"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
structopt = { version = "0.3", default-features = false }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
xml_writer = "0.4.0"
