[package]
name = "cyclonedx-bom"
version = "0.1.0"
authors = [ "Steve Springett <steve.springett@owasp.org>" ]
license = "Apache-2.0"
edition = "2018"

description = "CycloneDX Software Bill of Materials (SBOM) for Rust Crates"
homepage = "https://cyclonedx.org/"
repository = "https://github.com/CycloneDX/cyclonedx-rust-cargo"
readme = "README.md"

categories = ["command-line-utilities", "development-tools", "development-tools::cargo-plugins"]
keywords = ["sbom", "bom", "bill-of-materials", "components", "dependencies"]

[profile.release]
lto = true

[dependencies]
cargo = "0.35"
failure = "0.1"
structopt = "0.2"
regex = "1.3.6"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
packageurl = "0.2.0"
xml_writer = "0.4.0"
