name: Deploy cyclonedx-bom to Crates.io

on:
  push:
    tags:
      - 'cyclonedx-bom-[0-9]+.[0-9]+.[0-9]+*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish
        run: cargo publish --token ${{ secrets.CARGO_API_KEY }} --package cyclonedx-bom --verbose