name: Rust CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install Rust Toolchain
      run: |
        rustup update
        rustup component add clippy
        rustup install beta
        rustup install nightly
    - name: Build
      run: cargo build --verbose
    - name: Execute stable tests
      run: |
        cargo test --verbose
        cargo clippy
    - name: Execute beta tests
      run: cargo +beta test --verbose
    - name: Execute nightly tests
      run: cargo +nightly test --verbose
