name: Rust CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  lint:
    name: Linting & Coding Standards
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust Toolchain
      run: |
        rustup update
        rustup component add clippy
    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy

  test:
    name: Test Suite Runs - ${{ matrix.test-arm }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - # test with the current stable version
            test-arm: 'Stable'
            rust-version: 'stable'
            continue-on-error: false
          - # test with the MSRV version
            test-arm: 'Minimum Supported Rust Version'
            rust-version: '1.56.1'
            continue-on-error: false
          - # test with the current nightly version (allowed to fail)
            test-arm: 'Nightly'
            rust-version: 'nightly'
            continue-on-error: true

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust Toolchain
      run: |
        rustup update
        rustup install ${{ matrix.rust-version }}
    - name: Build
      run: cargo +${{ matrix.rust-version }} build --verbose
      continue-on-error: ${{ matrix.continue-on-error }}
    - name: Execute tests
      run: cargo +${{ matrix.rust-version }} test --verbose
      continue-on-error: ${{ matrix.continue-on-error }}
